# компоуз для деплоя в продакшн из dockerhub
version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nikson276/foodgram_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: nikson276/foodgram_frontend # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:     
      - static:/frontend_static
  gateway:
    image: nikson276/foodgram_gateway # Качаем с Docker Hub
    env_file: .env
    volumes:   
      - static:/staticfiles
      - media:/media
    ports:
      - 8000:80
