# User creation request
POST http://127.0.0.1:8000/api/users/
Content-type: application/json

{
    "email": "admin@admin.ru",
    "username": "newboy",
    "first_name": "NotProvided",
    "password": "fw9S3YJsyLG5Zjw"
}

###
{
  "email": "user7@ya.ru",
  "username": "user7",
  "first_name": "Вася",
  "last_name": "Пупкин",
  "password": "fw9S3YJsyLG5Zjw"
}

###
# Users token receiving part
POST http://127.0.0.1:8000/api/auth/token/login/
Content-type: application/json

{
  "password": "fw9S3YJsyLG5Zjw",
  "email": "admin@admin.ru"
}

###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token
Content-type: application/json

{
    "new_password": "123",
    "current_password": "fw9S3YJsyLG5Zjw"
}
###
# ______________________________ANonymus _________________________________________
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
###

GET http://127.0.0.1:8000/api/tags/
###
GET http://127.0.0.1:8000/api/users/1/
###
GET http://127.0.0.1:8000/api/users/me/
###
GET http://127.0.0.1:8000/api/users/10/
###
# _____________________________Users requests part ____________________

# ____________Admin
GET http://127.0.0.1:8000/api/users/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
GET http://127.0.0.1:8000/api/recipes/?limit=2
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
GET http://127.0.0.1:8000/api/users/2/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
GET http://127.0.0.1:8000/api/ingredients/?name=а
###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
Content-type: application/json

{
    "new_password": "123",
    "current_password": "fw9S3YJsyLG5Zjw"
}
###



# ____________USER 6 
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
POST http://127.0.0.1:8000/api/users/7/subscribe/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
DELETE http://127.0.0.1:8000/api/users/6/subscribe/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
##?limit=1&recipes_limit=4
GET http://127.0.0.1:8000/api/users/subscribtions/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/tags/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/ingredients/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/recipes/6/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
Content-type: application/json

{
    "ingredients": [
        {
            "id": 1,
            "amount": 10
        },
        {
            "id": 1,
            "amount": 10
        }
    ],
    "tags": [
        1,
        2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "Повторяющиеся теги",
    "text": "Проверка валидации",
    "cooking_time": 5
}

# ___________Favorite
###
POST http://127.0.0.1:8000/api/recipes/62/favorite/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
DELETE http://127.0.0.1:8000/api/recipes/17/favorite/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
POST http://127.0.0.1:8000/api/recipes/62/shopping_cart/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
DELETE http://127.0.0.1:8000/api/recipes/62/shopping_cart/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
#http://127.0.0.1:5500/api/recipes/download_shopping_cart/
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
###
GET http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=breakfast&tags=lunch&tags=diner
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###


# Recipe creation
#ADMIN
###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
Content-type: application/json

{
  "ingredients": [
    {
      "id": 102,
      "amount": 2000
    },
    {
      "id": 280,
      "amount": 2000
    },
    {
      "id": 11,
      "amount": 100
    },
    {
      "id": 886,
      "amount": 1500
    },
    {
      "id": 19,
      "amount": 3
    },
    {
      "id": 564,
      "amount": 0.5
    }
  ],
  "tags": [],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "LuLya-Kebab",
  "text": "Значит, готовим еду. Я беру сковороду. Потом на сковороду я эту, мать ее, курицу кладу. Потом туда в догонку ей подсолнечного масла. Еще немного перца и протертой сырной массы. Потом потру морковки и покрошу лучку, А чтоб не мучал запах, можно врезать коньячку",
  "cooking_time": 120
}
###
PATCH http://127.0.0.1:8000/api/recipes/62/
Authorization: Token 0422ba4c75436603caf5f6c97ba31a39f7852dbf
Content-type: application/json

{
    "ingredients": [
      {
        "id": 102,
        "amount": 2000
      }
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "Нет поля с ингредиентами",
    "text": "Ингредиенты не указаны",
    "cooking_time": 12
}
###
# USER 6
###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
Content-type: application/json

{
  "ingredients": [
    {
      "id": 102,
      "amount": 3000
    },
    {
      "id": 280,
      "amount": 1500
    },
    {
      "id": 11,
      "amount": 0.5
    },
    {
      "id": 886,
      "amount": 1000
    },
    {
      "id": 19,
      "amount": 1
    },
    {
      "id": 564,
      "amount": 2.5
    }
  ],
  "tags": [
    2,
    3
  ],
  "name": "Kazan-Mangal-Kebab",
  "text": "Значит, готовим еду. Я беру сковороду. Потом на сковороду я эту, мать ее, курицу кладу. Потом туда в догонку ей подсолнечного масла. Еще немного перца и протертой сырной массы. Потом потру морковки и покрошу лучку, А чтоб не мучал запах, можно врезать коньячку",
  "cooking_time": 60
}
###
