# User creation request
POST http://127.0.0.1:8000/api/users/
Content-type: application/json

{
  "email": "user7@ya.ru",
  "username": "user7",
  "first_name": "Вася",
  "last_name": "Пупкин",
  "password": "fw9S3YJsyLG5Zjw"
}

###
# Users token receiving part
POST http://127.0.0.1:8000/api/auth/token/login/
Content-type: application/json

{
  "password": "fw9S3YJsyLG5Zjw",
  "email": "user6@ya.ru"
}

###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token
Content-type: application/json

{
    "new_password": "123",
    "current_password": "fw9S3YJsyLG5Zjw"
}
###
# ______________________________ANonymus _________________________________________
GET http://127.0.0.1:8000/api/recipes/
###

GET http://127.0.0.1:8000/api/tags/
###
GET http://127.0.0.1:8000/api/users/
###
GET http://127.0.0.1:8000/api/users/me/
###
GET http://127.0.0.1:8000/api/users/2/
###
# _____________________________Users requests part ____________________

# ____________Admin
GET http://127.0.0.1:8000/api/users/
Authorization: Token 887d946ac671e57707b2125eb2260f456c025f62
###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 887d946ac671e57707b2125eb2260f456c025f62
###
GET http://127.0.0.1:8000/api/users/2/
Authorization: Token 887d946ac671e57707b2125eb2260f456c025f62
###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token 887d946ac671e57707b2125eb2260f456c025f62
Content-type: application/json

{
    "new_password": "123",
    "current_password": "fw9S3YJsyLG5Zjw"
}
###



# ____________USER 6 
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
POST http://127.0.0.1:8000/api/users/7/subscribe/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
DELETE http://127.0.0.1:8000/api/users/6/subscribe/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
##?limit=1&recipes_limit=4
GET http://127.0.0.1:8000/api/users/subscribtions/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/tags/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/ingredients/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
GET http://127.0.0.1:8000/api/recipes/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 1172388a9d06436513c59c8b67347c8e0dc437b2
Content-type: application/json

{
  "ingredients": [
    {
      "id": 18,
      "amount": 0.5
    },
    {
      "id": 2,
      "amount": 1
    }
  ],
  "tags": [
    2,
    3
  ],
  "name": "My recipe1",
  "text": "Значит, готовим еду. Я беру сковороду. Потом на сковороду я эту, мать ее, курицу кладу. Потом туда в догонку ей подсолнечного масла. Еще немного перца и протертой сырной массы. Потом потру морковки и покрошу лучку, А чтоб не мучал запах, можно врезать коньячку",
  "cooking_time": 15
}
###

DELETE http://127.0.0.1:8000/api/recipes/5/
Authorization: Token 887d946ac671e57707b2125eb2260f456c025f62
###