# Generated by Django 3.2.3 on 2024-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='г', max_length=15, verbose_name='ЕИ'),
        ),
    ]
