# Generated by Django 3.2.3 on 2024-02-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240209_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_shoplist', to='recipes.recipe'),
        ),
    ]
