# Generated by Django 3.2.3 on 2024-02-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20240219_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',)},
        ),
    ]
