# Generated by Django 3.2.3 on 2024-02-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-12 23:00:00.000000', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
